import Head from 'next/head';
import { Button } from '@pinklemon/ui';

export default function Home() {
  return (
    <>
      <Head>
        <title>@pinklemon/playground</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>
          <h1>Playground</h1>
          <Button onClick={() => alert('Funcionou!')}>Testar botão</Button>
        </div>
      </main>
    </>
  );
}
